version: '3.1.8'
services:
  springboot-app:
    build:
      context: /home/hjhgjhgjhg/IdeaProjects/wswork-desafio-tecnico
      dockerfile: /home/hjhgjhgjhg/IdeaProjects/wswork-desafio-tecnico/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - wswork-net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/wswork
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - postgres-db
    command: ["/wait-for-it.sh postgres-db:5432 -t 60 -- java -Djava.security.egd=file:/dev/./urandom -jar /app/projeto-0.0.1-SNAPSHOT.jar
"]

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    networks:
      - wswork-net
    environment:
      - POSTGRES_DB=wswork
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

networks:
  wswork-net: